import { calendar, locations } from '../data';
import { computeAll } from '../engine/status';
import { EMPTY_LIVE, isLiveData, LIVE_SOURCES, usableLive, type LiveData } from '../engine/live';
import { record } from '../engine/validation';
import { fetchAllLive } from './live';

export interface Env {
  ASSETS: Fetcher;
}

/** How long a live snapshot is served before a background refresh is triggered. */
const LIVE_FRESH_MS = 60_000;
/** Hard cap on how old a snapshot may be before we block on a fresh fetch. */
const LIVE_MAX_AGE_MS = 15 * 60_000;
// Older snapshots lack structured interval access or the Bray calendar source and must be fetched again.
const LIVE_CACHE_KEY = 'https://live.tufts-is-it-open.internal/snapshot-v3';

let memory: { data: LiveData; at: number } | undefined;
let inflight: Promise<LiveData> | undefined;

const edgeCache = (): Cache => (caches as unknown as { default: Cache }).default;

async function refreshLive(ctx: ExecutionContext): Promise<LiveData> {
  if (inflight) return inflight;
  inflight = (async () => {
    const data = await fetchAllLive(new Date());
    memory = { data, at: Date.now() };
    try {
      const cache = edgeCache();
      await cache.put(
        LIVE_CACHE_KEY,
        new Response(JSON.stringify(memory), { headers: { 'content-type': 'application/json', 'cache-control': 'max-age=3600' } }),
      );
    } catch {
      /* cache unavailable (e.g. local dev) */
    }
    return data;
  })();
  try {
    return await inflight;
  } finally {
    inflight = undefined;
    void ctx;
  }
}

async function getLive(ctx: ExecutionContext, healthCheck = false): Promise<LiveData> {
  if (!memory) {
    try {
      const hit = await edgeCache().match(LIVE_CACHE_KEY);
      if (hit) {
        const value: unknown = await hit.json();
        if (record(value) && isLiveData(value.data)) memory = { data: value.data, at: Date.parse(value.data.fetchedAt) };
      }
    } catch {
      /* ignore */
    }
  }
  const age = memory ? Date.now() - memory.at : Infinity;
  // Readiness accepts cached provider successes until the hours TTL; probes do not refresh every minute.
  if (healthCheck && memory && age >= 0 && age < LIVE_MAX_AGE_MS) {
    return { ...memory.data, sources: age < LIVE_FRESH_MS ? memory.data.sources : markStale(memory.data.sources) };
  }
  if (memory && age >= 0 && age < LIVE_FRESH_MS) return usableLive(memory.data, new Date());
  if (memory && age < LIVE_MAX_AGE_MS) {
    ctx.waitUntil(refreshLive(ctx).catch(() => undefined));
    return usableLive({ ...memory.data, sources: markStale(memory.data.sources) }, new Date());
  }
  try {
    return await refreshLive(ctx);
  } catch {
    // Whatever we still have is older than the freshness window: say so.
    return usableLive(memory?.data ?? EMPTY_LIVE, new Date(), true);
  }
}

function markStale(sources: LiveData['sources']): LiveData['sources'] {
  const out: LiveData['sources'] = {};
  for (const [k, v] of Object.entries(sources)) out[k] = v === 'ok' ? 'stale' : v;
  return out;
}

function json(body: unknown, init: ResponseInit = {}): Response {
  return new Response(JSON.stringify(body), {
    ...init,
    headers: {
      'content-type': 'application/json; charset=utf-8',
      'access-control-allow-origin': '*',
      'cache-control': 'public, max-age=30',
      ...(init.headers ?? {}),
    },
  });
}

function parseAt(url: URL): Date {
  const at = url.searchParams.get('at');
  if (!at) return new Date();
  const d = new Date(at);
  return Number.isNaN(d.getTime()) ? new Date() : d;
}

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);
    const path = url.pathname;

    // The homepage is a static asset (public/index.html, generated by `npm run build`); the assets layer
    // serves it before this Worker runs, so only the API and unknown paths reach this handler.
    if (path === '/api/live') {
      const live = await getLive(ctx);
      return json(live);
    }

    if (path === '/api/status') {
      const at = parseAt(url);
      const live = await getLive(ctx);
      const statuses = computeAll(locations, calendar, at, live.overrides);
      const byId = new Map(locations.map((l) => [l.id, l]));
      return json({
        at: at.toISOString(),
        timezone: 'America/New_York',
        liveFetchedAt: live.fetchedAt || null,
        locations: statuses.map((s) => {
          const loc = byId.get(s.id)!;
          return {
            id: s.id,
            name: loc.name,
            category: loc.category,
            state: s.state,
            label: s.label,
            detail: s.detail,
            period: s.period ?? null,
            today: s.today,
            scheduleNote: s.scheduleNote ?? null,
            nextDepartures: s.nextDepartures ?? null,
            vehicles: live.vehicles[s.id] ?? null,
            links: loc.links,
          };
        }),
      });
    }

    // Older browser bundles may still send events after deployment.
    if (path === '/api/event') return new Response(null, { status: 410 });

    if (path === '/api/locations') {
      return json({ calendar, locations }, { headers: { 'cache-control': 'public, max-age=3600' } });
    }

    if (path === '/healthz') {
      const live = await getLive(ctx, true);
      const ok = LIVE_SOURCES.every((id) => ['ok', 'stale'].includes(live.sources[id] ?? '')) && !live.failedLocations?.length;
      return json({ ok, fetchedAt: live.fetchedAt || null, ageSeconds: live.fetchedAt ? Math.max(0, Math.floor((Date.now() - Date.parse(live.fetchedAt)) / 1000)) : null,
        sources: live.sources, failedLocations: live.failedLocations ?? [] },
      { status: ok ? 200 : 503, headers: { 'cache-control': 'no-store' } });
    }

    return env.ASSETS.fetch(request);
  },
} satisfies ExportedHandler<Env>;
